Remove ks dependency
WeTransfer/image_vise pull request #46
Opened 2021-07-29 10:58 UTC by kodnin

Remove `ks` gem as it breaks Ruby 3 compatibility. `image_vise` is (still) used in https://github.com/WeTransfer/spaceship.

2021-07-30 07:42 UTC, kodnin commented
Reminder: we need to look into what Ruby versions are supported, because not all have this `Struct` option yet. That was the whole point of the `ks` gem.

2021-07-30 08:46 UTC, fabioperrella commented
Well, we can bump the major and remove support of old Rubies.

As a suggestion, you can change this project to use Github Actions as I proposed here https://github.com/WeTransfer/sqewer/pull/88

2021-08-04 13:18 UTC, kodnin commented
> Well, we can bump the major and remove support of old Rubies.
> 
> As a suggestion, you can change this project to use Github Actions as I proposed here [WeTransfer/sqewer#88](https://github.com/WeTransfer/sqewer/pull/88)

I'm currently awaiting a response on https://github.com/WeTransfer/image_vise_standalone/issues/300#issuecomment-892649130.

2021-08-10 13:00 UTC, kodnin commented on .travis.yml
> -sudo: false
This has no effect anymore.

2021-08-10 22:07 UTC, julik requested changes
The `ks` removal is perfect 😍  but there are a couple of other points we should probably look into

2021-08-10 22:07 UTC, julik commented on CHANGELOG.md
> +* Add `addressable` runtime dependency
Why do we need to depend on Addressable? GIven that this is a library. Are there any features in Addressable we are using which are not provided by `uri` from stdlib?

2021-08-10 22:07 UTC, julik commented on image_vise.gemspec
> +  spec.required_ruby_version = ">= 2.7"
Is there any reason we need to require 2.7+? Keyword init for structs is available since 2.5 and even a few internal WT apps are still using 2.6+

2021-08-10 22:07 UTC, julik commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
Is the 2.7 keyword argument treatment the reason we need to require 2.7? If so it is unpleasant but there likely is a solution we could try to stay backwards-compatible

2021-08-11 08:24 UTC, kodnin commented on CHANGELOG.md
> +* Add `addressable` runtime dependency
Good question! `URI.encode`/`URI.escape` and `URI.decode/URI.unescape` have been removed in Ruby 3. For Ruby 3 you have to work with `URI.encode_www_form` or `URI.encode_www_form_component`, which have a different API. I tried those, but it was a hassle to get that working. Also, I could only test it on Travis CI and not locally, making matters more difficult. Keeping the time invested already in mind I went for the pragmatic solution proposed in https://github.com/docusign/docusign-esign-ruby-client/issues/45. More context can be found here https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string. Feel free to have a try, as it should be possible, but I can't really spend more time on this than I have.

2021-08-11 08:27 UTC, kodnin commented on image_vise.gemspec
> +  spec.required_ruby_version = ">= 2.7"
@fabioperrella suggested to only support the stable releases. Ruby 2.5 is not maintained anymore and the security maintenance for 2.6 will also end soon (https://www.ruby-lang.org/en/downloads/). I'm happy to lower this, but I'll leave that decision up to you and Fabio.

2021-08-11 08:29 UTC, kodnin commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
It's the keyword argument treatment in Ruby 3 that is the problem (https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/). Ruby 2.7 builds fine without this change, Ruby 3 doesn't. Do you have a suggestion to make it backwards-compatible?

2021-08-11 08:31 UTC, kodnin commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
Just wondering, isn't it backwards compatible already?

2021-08-11 09:15 UTC, fabioperrella commented on image_vise.gemspec
> +  spec.required_ruby_version = ">= 2.7"
@julik is there a reason to keep compatibility with EOL Ruby versions?

@kodnin I think we need to support `>= 2.6` because the end of life will happen only in 7 months -> https://endoflife.date/ruby, wdyt?

2021-08-11 09:20 UTC, fabioperrella commented on image_vise.gemspec
> +  spec.add_dependency "addressable"
```suggestion
  spec.add_dependency 'addressable', '>= 2', '< 3'
```

What about setting a range of versions that we trust that it will work? (the current version is 2.8)

2021-08-11 09:24 UTC, fabioperrella commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
It looks like it is, I think

As I suggested in another discussion, if we add support to Ruby 2.6 as well, Travis will tell us if this works 😄

2021-08-11 10:27 UTC, kodnin commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
It is not: https://app.travis-ci.com/github/WeTransfer/image_vise/jobs/530652721.

2021-08-11 11:22 UTC, kodnin commented on image_vise.gemspec
> +  spec.required_ruby_version = ">= 2.7"
I'm trying to make it work for Ruby 2.6.

2021-08-11 11:33 UTC, kodnin commented on lib/image_vise/pipeline.rb
> +  if RUBY_VERSION.start_with?("2.6")
It doesn't make me proud, but it does the job. 🤷 Any other suggestions?

2021-08-11 11:59 UTC, kodnin commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
There you go, https://github.com/WeTransfer/image_vise/pull/46/commits/fd583fb0a2a61383be00867221fde860b427e2cf.

2021-08-11 11:59 UTC, kodnin commented on image_vise.gemspec
> +  spec.required_ruby_version = ">= 2.7"
It works™.

2021-08-11 12:43 UTC, fabioperrella commented on lib/image_vise/pipeline.rb
> +    self << operator_builder.new(**args)
it is good for me!

2021-08-11 12:45 UTC, fabioperrella approved these changes
nice job!

2021-08-17 01:55 UTC, merged

2021-08-17 08:43 UTC, fabioperrella commented
@julik I would like to understand why we still need to support Ruby 2.5 which is already an EOL version

2021-08-17 10:45 UTC, julik commented
@fabioperrella Sure! I think removing support for something on a library that people use is a balance between effort to keep supporting it and the use of the library by others. Even though a version of Ruby is EOL, as long as we can cheaply test against it (and it doesn't require too many workarounds) when we are providing _a library_ we should keep support for older versions as long as is practical. I use image_vise in a few of my own apps, and I don' remember which ones of them are still on 2.5 - just an example. So I try to look at it from the perspective of a user: if we drop support for a runtime version, we cause them inconvenience. Some would not be able to update image_vise due to this requirement because their app might be using something that can't run on 2.6+.

So: the line of thought that I have here is that if it is not a large effort to maintain compatibility with older versions of Ruby we, as library authors, absolutely should maintain it.

2021-08-17 13:14 UTC, fabioperrella commented
ok got it, thank you for the explanation!